### ISSUE TITLE
'OBForceField' object has no attribute 'DiverseConfGen' on Windows

### ISSUE THREAD

**Issue by DanielYang59** [njzjz/openbabel-wheel#34]
Hi @njzjz,

Thanks a lot for making these wheels, my life is much easier with them. 

I noticed the following failure on `openbabel-wheel==3.1.1.19` on Windows for both [the `pymatgen` CI](https://github.com/materialsproject/pymatgen/actions/runs/10401917112/job/28805345429?pr=3985) and locally. I'm not sure whether it's an intrinsic issue of `Open Babel` or the wheel to start with.

```python
from openbabel import openbabel


ff = openbabel.OBForceField.FindType("mmff94")
ff.DiverseConfGen(0.5, 100000, 50)
```

Raises:
```
Traceback (most recent call last):
  File "z:\test\debug-openbabel.py", line 7, in <module>
    ff.DiverseConfGen(0.5, 100000, 50)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'OBForceField' object has no attribute 'DiverseConfGen'
```

**Comment by njzjz** [comment]
Reproduced.

**Comment by njzjz** [comment]
The reason is that `DiverseConfGen` is only available when eigen is enabled, and I have no idea how to install the eigen on Windows, with the GitHub Actions and cibuildwheel stuff.

https://github.com/openbabel/openbabel/blob/7acf50c9d73f8016e15eb2a45ce74c8909152883/scripts/openbabel-python.i#L91-L99

**Comment by njzjz** [comment]
> I have no idea how to install the eigen on Windows, with the GitHub Actions and cibuildwheel stuff.

Oh I noticed [rdkit-pypi](https://github.com/kuelumbus/rdkit-pypi) has done some work.

**Comment by DanielYang59** [comment]
Hi @njzjz thanks a lot for the quick response and diagnosing! I really appreciate that work and let me know should there be anything I could assist in.
